In [1]:
import pandas as pd
import numpy as np 
df = pd.read_csv('train.csv')

In [2]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
  Starting server from c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\DRSAND~1\AppData\Local\Temp\tmp20cxcgi7
  JVM stdout: C:\Users\DRSAND~1\AppData\Local\Temp\tmp20cxcgi7\h2o_drsandeepabrol_started_from_python.out
  JVM stderr: C:\Users\DRSAND~1\AppData\Local\Temp\tmp20cxcgi7\h2o_drsandeepabrol_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321... successful.

--------------------------  -------------------------------------
H2O cluster uptime:         03 secs
H2O cluster timezone:       America/New_York
H2O data parsing timezone:  UTC
H2O cluster version:        3.18.0.11
H2O cluster version age:    1 month and 10 days
H2O cluster name:           H2O_from_python_drsandeepabrol_6obewq
H2O cluster total nodes:    1
H2O cluster free memory:    1.757 Gb
H2O cluster total cores:    4
H2O cluster allowed cores:  4
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://127.0.0.1:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Algos, AutoML, Core V3, Core V4
Python version:             3.6.5 final
--------------------------  -------------------------------------

In [6]:
hf=h2o.H2OFrame(df)

c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\utils\shared_utils.py:170: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  data = _handle_python_lists(python_obj.as_matrix().tolist(), -1)[1]

Parse progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%

In [ ]:
from h2o.automl import H2OAutoML
x=hf.columns
y='SalePrice'
hf['SalePrice']=hf['SalePrice'].asfactor()
for r in ['Id',y]:
    x.remove(r)
    
aml = H2OAutoML(max_runtime_secs = 60)
aml.train(x = x, y = y,
          training_frame = hf)

In [ ]:
aml.leaderboard

In [15]:
test=h2o.H2OFrame(pd.read_csv('test.csv'))
preds=aml.predict(test)
final=test.cbind(preds)
results=h2o.as_list(final)

c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\utils\shared_utils.py:170: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  data = _handle_python_lists(python_obj.as_matrix().tolist(), -1)[1]

Parse progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%
Parse progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%
drf prediction progress: |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 100%

c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'MSZoning' has levels not trained on: [nan]
  warnings.warn(w)
c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'Utilities' has levels not trained on: [nan]
  warnings.warn(w)
c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'Exterior1st' has levels not trained on: [nan]
  warnings.warn(w)
c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'Exterior2nd' has levels not trained on: [nan]
  warnings.warn(w)
c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'KitchenQual' has levels not trained on: [nan]
  warnings.warn(w)
c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'Functional' has levels not trained on: [nan]
  warnings.warn(w)
c:\users\drsandeepabrol\appdata\local\programs\python\python36\lib\site-packages\h2o\job.py:69: UserWarning: Test/Validation dataset column 'SaleType' has levels not trained on: [nan]
  warnings.warn(w)

In [17]:
results.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,p485000,p501837,p538000,p555000,p556581,p582933,p611657,p625000,p745000,p755000
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,0.0,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0.0,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000028,0.000053,0.000291
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0.0,0.00000,0.000000,0.000149,0.00000,0.000000,0.000149,0.000108,0.000000,0.000000
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0.0,0.00000,0.000000,0.000135,0.00000,0.000000,0.000135,0.038326,0.000000,0.000000
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,0.0,0.00092,0.001356,0.000000,0.00092,0.000352,0.000000,0.000042,0.000000,0.000000

In [22]:
odf=results.loc[:,['Id','predict']]
odf.columns=['Id','SalePrice']
odf.to_csv('submission.csv',index=False)